import { generateHTML, generateCSS, generateReact } from './codegen';
import type { GridState } from './types';
import { COLOR_MAP } from './constants';
import JSZip from 'jszip';

export async function downloadProjectZip(state: GridState) {
    const zip = new JSZip();
    const html = generateHTML(state);
    const css = generateCSS(state);

    zip.file("index.html", html);
    zip.file("style.css", css);
    zip.file("README.md", `# Grid Master Project\n\nGenerated with Grid Master.\n\n## Files\n- index.html: Self-contained preview\n- style.css: Raw CSS styles`);

    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = "grid-master-project.zip";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

export function openInCodePen(state: GridState) {
    const css = generateCSS(state, 'grid-container');
    const { areas } = state;

    const htmlBody = `<!-- Generated by Grid Master -->
<div class="grid-container">
  ${areas.map(a => `<${a.tag || 'div'} class="${a.name}">
    <span>${a.name}</span>
  </${a.tag || 'div'}>`).join('\n  ')}
</div>`;

    const visualCSS = `
body {
  margin: 0;
  padding: 2rem;
  font-family: system-ui, -apple-system, sans-serif;
  background-color: #f1f5f9;
  color: #0f172a;
}

.grid-container {
  background-color: #ffffff;
  border-radius: 0.5rem;
  box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);
  min-height: 80vh;
  padding: 1rem;
}

/* Area Visualization Styles */
${areas.map(a => `
.${a.name} {
  background-color: ${a.color.startsWith('#') ? a.color : '#e2e8f0'};
  /* fallback color if hex is invalid/missing */
  background-color: ${a.color.startsWith('#') ? a.color : `var(--color-${a.name}, #cbd5e1)`};
  color: #1e293b;
  padding: 1rem;
  border-radius: 0.25rem;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: bold;
  border: 1px solid rgba(0,0,0,0.05);
}`).join('\n')}
`;

    const data = {
        title: "Grid Master Layout",
        description: "Generated with Grid Master",
        html: htmlBody,
        css: css + '\n' + visualCSS,
        editors: "110" // HTML & CSS open
    };

    const form = document.createElement('form');
    form.action = 'https://codepen.io/pen/define';
    form.method = 'POST';
    form.target = '_blank';

    const input = document.createElement('input');
    input.type = 'hidden';
    input.name = 'data';
    input.value = JSON.stringify(data);
    form.appendChild(input);

    document.body.appendChild(form);
    form.submit();
    document.body.removeChild(form);
}

export async function downloadPNG(state: GridState, theme = 'standard') {
    // Determine dimensions based on track definitions if possible, or default to HD
    // We'll use a larger default for PNG export for crispness
    const width = 1200;
    const height = 800;

    const svgString = generateSVG(state, theme, width, height);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const img = new Image();

    const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    img.onload = () => {
        canvas.width = width;
        canvas.height = height;
        if (ctx) {
            ctx.fillStyle = theme === 'cyber' ? '#111' : '#fff';
            ctx.fillRect(0, 0, width, height);
            ctx.drawImage(img, 0, 0);
        }

        canvas.toBlob((pngBlob) => {
            if (pngBlob) {
                const pngUrl = URL.createObjectURL(pngBlob);
                const a = document.createElement('a');
                a.href = pngUrl;
                a.download = `grid-master-${theme}.png`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(pngUrl);
            }
            URL.revokeObjectURL(url);
        });
    };

    img.src = url;
}

export async function copyReactComponent(state: GridState) {
    const code = generateReact(state);
    try {
        await navigator.clipboard.writeText(code);
        return true;
    } catch (e) {
        console.error('Failed to copy', e);
        return false;
    }
}

export function openInStackBlitz(html: string) {
    const form = document.createElement('form');
    form.method = 'POST';
    form.action = 'https://stackblitz.com/run';
    form.target = '_blank';

    const inputHtml = document.createElement('input');
    inputHtml.type = 'hidden';
    inputHtml.name = 'project[files][index.html]';
    inputHtml.value = html;
    form.appendChild(inputHtml);

    const inputTitle = document.createElement('input');
    inputTitle.type = 'hidden';
    inputTitle.name = 'project[title]';
    inputTitle.value = 'Grid Master Layout';
    form.appendChild(inputTitle);

    const inputDesc = document.createElement('input');
    inputDesc.type = 'hidden';
    inputDesc.name = 'project[description]';
    inputDesc.value = 'Layout generated with Grid Master';
    form.appendChild(inputDesc);

    const inputTemplate = document.createElement('input');
    inputTemplate.type = 'hidden';
    inputTemplate.name = 'project[template]';
    inputTemplate.value = 'html';
    form.appendChild(inputTemplate);

    document.body.appendChild(form);
    form.submit();
    document.body.removeChild(form);
}

export function downloadProjectHtml(state: GridState) {
    const html = generateHTML(state);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'grid-master-project.html';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

export function generateSVG(state: GridState, theme = 'standard', width = 800, height = 600): string {
    const parseTrack = (track: string, available: number) => {
        if (track.endsWith('px')) return parseFloat(track);
        if (track.endsWith('%')) return (parseFloat(track) / 100) * available;
        if (track === 'auto' || track.includes('minmax') || track.includes('fit-content')) return 100; // arbitrary fallback
        if (track.endsWith('fr')) return parseFloat(track);
        return 100;
    };

    const rowDefs = state.rows.map(r => ({ raw: r, val: parseTrack(r, height), type: r.endsWith('fr') ? 'fr' : 'fixed' }));
    const colDefs = state.cols.map(c => ({ raw: c, val: parseTrack(c, width), type: c.endsWith('fr') ? 'fr' : 'fixed' }));

    const totalFixedH = rowDefs.filter(r => r.type === 'fixed').reduce((a, b) => a + b.val, 0);
    const totalFrH = rowDefs.filter(r => r.type === 'fr').reduce((a, b) => a + b.val, 0);
    const availableH = Math.max(0, height - totalFixedH);

    const totalFixedW = colDefs.filter(c => c.type === 'fixed').reduce((a, b) => a + b.val, 0);
    const totalFrW = colDefs.filter(c => c.type === 'fr').reduce((a, b) => a + b.val, 0);
    const availableW = Math.max(0, width - totalFixedW);

    // Calculate start positions
    const rowPos = [0];
    rowDefs.forEach(r => {
        let size = r.val;
        if (r.type === 'fr') {
            size = (r.val / (totalFrH || 1)) * availableH;
        }
        rowPos.push(rowPos[rowPos.length - 1] + size);
    });

    const colPos = [0];
    colDefs.forEach(c => {
        let size = c.val;
        if (c.type === 'fr') {
            size = (c.val / (totalFrW || 1)) * availableW;
        }
        colPos.push(colPos[colPos.length - 1] + size);
    });

    // Generate Areas
    let rects = '';
    const fontSize = 14;

    state.areas.forEach(area => {
        const r1 = area.rowStart - 1;
        const r2 = area.rowEnd - 1;
        const c1 = area.colStart - 1;
        const c2 = area.colEnd - 1;

        if (r1 >= rowPos.length || c1 >= colPos.length) return;

        const y = rowPos[r1];
        const h = Math.max(0, (rowPos[r2] || height) - y);
        const x = colPos[c1];
        const w = Math.max(0, (colPos[c2] || width) - x);

        // Apply theme colors
        let fill = area.color.startsWith('#') ? area.color : COLOR_MAP[area.color] || '#cbd5e1';
        let stroke = 'none';
        let textFill = '#1e293b'; // slate-800
        let strokeWidth = 0;

        if (theme === 'blueprint') {
            fill = '#1e3a8a'; // blue-900
            stroke = '#60a5fa'; // blue-400
            strokeWidth = 2;
            textFill = '#ffffff';
        } else if (theme === 'wireframe') {
            fill = '#ffffff';
            stroke = '#94a3b8'; // slate-400
            strokeWidth = 2;
            textFill = '#000000';
        } else if (theme === 'cyber') {
            fill = '#000000';
            stroke = '#00ff00';
            strokeWidth = 2;
            textFill = '#00ff00';
        }

        // Adjust opacity for fill in blueprint/wireframe
        const fillOpacity = theme === 'standard' ? 1 : (theme === 'blueprint' ? 0.5 : 0.1);

        rects += `
            <g>
                <rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${fill}" fill-opacity="${fillOpacity}" stroke="${stroke}" stroke-width="${strokeWidth}" />
                <text x="${x + w/2}" y="${y + h/2}" font-family="sans-serif" font-size="${fontSize}" fill="${textFill}" text-anchor="middle" dominant-baseline="middle" font-weight="bold">
                    ${area.name}
                </text>
            </g>
        `;
    });

    const bg = theme === 'cyber' ? '#111' : (theme === 'blueprint' ? '#eff6ff' : '#f8fafc');

    return `
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
    <rect width="100%" height="100%" fill="${bg}" />
    ${rects}
</svg>
    `.trim();
}

export function downloadSVG(state: GridState, theme = 'standard') {
    const svg = generateSVG(state, theme);
    const blob = new Blob([svg], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `grid-master-${theme}.svg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
