export interface AnalysisData {
  hashes?: Record<string, string>;
  magic?: {
    description: string;
    type: string;
    matches: boolean;
  };
  entropy?: number;
  hexPreview?: string;
}

export function generateReport(file: File | null, data: AnalysisData): string {
  const timestamp = new Date().toISOString();

  let report = `FILE FORGE ANALYSIS REPORT\n`;
  report += `Generated: ${timestamp}\n`;
  report += `==================================================\n\n`;

  if (file) {
    report += `[FILE METADATA]\n`;
    report += `Name: ${file.name}\n`;
    report += `Size: ${file.size} bytes\n`;
    report += `Type: ${file.type || 'Unknown'}\n`;
    report += `Last Modified: ${new Date(file.lastModified).toISOString()}\n\n`;
  } else {
    report += `[FILE METADATA]\n`;
    report += `File source not available (Restored from history)\n\n`;
  }

  if (data.hashes) {
    report += `[CRYPTOGRAPHIC HASHES]\n`;
    for (const [algo, hash] of Object.entries(data.hashes)) {
      report += `${algo.toUpperCase()}: ${hash}\n`;
    }
    report += `\n`;
  }

  if (data.magic) {
    report += `[FILE TYPE IDENTIFICATION]\n`;
    report += `Detected Description: ${data.magic.description}\n`;
    report += `Detected MIME: ${data.magic.type}\n`;
    report += `Extension Match: ${data.magic.matches ? 'YES' : 'NO'}\n\n`;
  }

  if (data.entropy !== undefined) {
    report += `[ENTROPY ANALYSIS]\n`;
    report += `Shannon Entropy: ${data.entropy.toFixed(3)} / 8.0\n`;
    report += `Interpretation: ${
      data.entropy > 7.5 ? 'High (Likely Compressed/Encrypted)' :
      data.entropy < 5 ? 'Low (Likely Text/Simple)' : 'Moderate'
    }\n\n`;
  }

  if (data.hexPreview) {
    report += `[HEX PREVIEW (First 512 Bytes)]\n`;
    report += data.hexPreview;
    report += `\n`;
  }

  report += `==================================================\n`;
  report += `Generated by File Forge - MicroFactory\n`;

  return report;
}
