<script lang="ts">
  import GuideSection from '$lib/components/GuideSection.svelte';
  import AdPlaceholder from '$lib/components/AdPlaceholder.svelte';
  import RelatedTools from '$lib/components/RelatedTools.svelte';
  import Head from '$lib/components/Head.svelte';
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { getDictionary } from '$lib/dictionaries';
  import { MoveLeft, Download, Save, History, Share2, FileCode, Layers, FileJson, FileText } from '@lucide/svelte';
  import JSZip from 'jszip';

  import StackSelector from './components/StackSelector.svelte';
  import DatabaseSelector from './components/DatabaseSelector.svelte';
  import ConfigPanel from './components/ConfigPanel.svelte';
  import CodePreview from './components/CodePreview.svelte';

  import FAQSection from '$lib/components/FAQSection.svelte';
  import { STACKS } from '$lib/utils/deploy-forge/defaults';
  import type { StackId, ProjectConfig, DatabaseId } from '$lib/utils/deploy-forge/types';
  import { generateDockerfile, generateDockerignore } from '$lib/utils/deploy-forge/generator';
  import { generateCompose, generateEnv, generateEnvExample } from '$lib/utils/deploy-forge/compose';
  import { saveProject, getProjects, db } from '$lib/db/deploy-forge';

  // --- State ---
  $: lang = $page.params.lang || 'en';
  // Fallback for missing dictionary entries if any
  $: dict = getDictionary(lang);

  let currentStackId: StackId = 'node';
  let config: ProjectConfig = {
      port: 3000,
      baseImage: 'node:20-alpine',
      envVars: [],
      databases: [],
      buildCmd: '',
      startCmd: ''
  };

  let activeTab: 'dockerfile' | 'compose' | 'env' | 'ignore' = 'dockerfile';
  let showHistory = false;

  // --- Reactivity ---
  $: dockerfile = generateDockerfile(currentStackId, config);
  $: compose = generateCompose(config);
  $: envFile = generateEnv(config);
  $: envExampleFile = generateEnvExample(config);
  $: dockerIgnore = generateDockerignore(currentStackId);

  $: previewCode = activeTab === 'dockerfile' ? dockerfile
                 : activeTab === 'compose' ? compose
                 : activeTab === 'env' ? envFile
                 : dockerIgnore;

  $: previewLang = activeTab === 'dockerfile' ? 'docker'
                 : activeTab === 'compose' ? 'yaml'
                 : activeTab === 'env' ? 'bash' // close enough
                 : 'plaintext';

  $: faqItems = [
    { q: dict.tools.deployForge.q1, a: dict.tools.deployForge.a1 },
    { q: dict.tools.deployForge.q2, a: dict.tools.deployForge.a2 },
    { q: dict.tools.deployForge.q3, a: dict.tools.deployForge.a3 }
  ];

  // --- Actions ---

  function handleStackSelect(e: CustomEvent<StackId>) {
      const newStackId = e.detail;
      if (newStackId === currentStackId) return;

      currentStackId = newStackId;
      const def = STACKS.find(s => s.id === newStackId);
      if (def) {
          config = {
              ...config,
              baseImage: def.defaultImage,
              port: def.defaultPort,
              buildCmd: '', // Reset commands as they are stack specific
              startCmd: ''
          };
      }
  }

  function handleDbChange(e: CustomEvent<DatabaseId[]>) {
      config.databases = e.detail;
  }

  async function downloadProject() {
      const zip = new JSZip();

      zip.file('Dockerfile', dockerfile);
      zip.file('docker-compose.yml', compose);
      zip.file('.dockerignore', dockerIgnore);
      zip.file('.env', envFile);
      zip.file('.env.example', envExampleFile);

      // Add README
      zip.file('README.md', `# Project Configuration\n\nGenerated by Deploy Forge.\n\n## Stack\n- ${currentStackId}\n- Base Image: ${config.baseImage}\n\n## Usage\n\n\`\`\`bash\ndocker-compose up --build\n\`\`\``);

      const content = await zip.generateAsync({ type: 'blob' });
      const url = window.URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = `deploy-forge-${currentStackId}.zip`;
      a.click();
      window.URL.revokeObjectURL(url);
  }

  async function saveToHistory() {
      await saveProject({
          id: crypto.randomUUID(),
          name: `${currentStackId} - ${new Date().toLocaleTimeString()}`,
          stackId: currentStackId,
          config: { ...config }, // Clone
          updatedAt: Date.now()
      });
      // Show toast or feedback?
      alert(dict.tools.deployForge.saved);
  }
</script>
<Head
  url={"https://selfgrowingmicrotool.com/" + lang + "/tools/deploy-forge"}
  title={`${dict.tools.deployForge.title} | ${dict.home.title}`}
  description={dict.tools.deployForge.description}
  keywords="dockerfile generator, docker compose builder, container architect, devops tool"
/>



<div class="min-h-screen bg-slate-900 text-slate-100 pb-20">
  <!-- Header -->
  <header class="bg-slate-800/50 backdrop-blur-md border-b border-slate-700/50 sticky top-0 z-30">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
      <div class="flex items-center space-x-4">
        <a href="/{lang}" class="p-2 hover:bg-slate-700 rounded-full transition-colors group min-h-[44px] min-w-[44px] flex items-center justify-center" aria-label="Back">
          <MoveLeft size={20} class="text-slate-400 group-hover:text-white" />
        </a>
        <h1 class="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-cyan-400">
          {dict.tools.deployForge.title}
        </h1>
      </div>
      <div class="flex items-center space-x-2">
         <button on:click={saveToHistory} class="p-2 hover:bg-slate-700 rounded-lg text-slate-400 hover:text-white transition-colors min-h-[44px] min-w-[44px] flex items-center justify-center" aria-label={dict.tools.deployForge.save}>
            <Save size={20} />
         </button>
     <button on:click={downloadProject} class="flex items-center justify-center gap-2 px-3 sm:px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium transition-colors text-sm min-h-[44px] min-w-[44px]">
            <Download size={18} />
        <span class="hidden sm:inline">{dict.tools.deployForge.download}</span>
         </button>
      </div>
    </div>
  </header>

  <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">

        <!-- Left Column: Config (5 cols) -->
        <div class="lg:col-span-5 space-y-8">
            <section>
                <h2 class="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">{dict.tools.deployForge.selectStack}</h2>
                <StackSelector
                    selectedStackId={currentStackId}
                    on:select={handleStackSelect}
                />
            </section>

            <section class="bg-slate-900/50 p-6 rounded-2xl border border-slate-800">
                <ConfigPanel
                    bind:config
                    stackId={currentStackId}
                />
            </section>

            <section>
                <h2 class="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">{dict.tools.deployForge.addServices}</h2>
                <DatabaseSelector
                    selectedDatabases={config.databases}
                    on:change={handleDbChange}
                />
            </section>
        </div>

        <!-- Right Column: Preview (7 cols) -->
        <div class="lg:col-span-7">
            <div class="bg-slate-800 rounded-2xl border border-slate-700 shadow-xl overflow-hidden sticky top-24">
                <!-- Tabs -->
                <div class="flex items-center border-b border-slate-700 bg-slate-900/50 overflow-x-auto">
                    <button
                        class="flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                        {activeTab === 'dockerfile' ? 'border-indigo-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'} min-h-[44px] min-w-[44px]"
                        on:click={() => activeTab = 'dockerfile'}
                    >
                        <FileCode size={16} /> Dockerfile
                    </button>
                    <button
                        class="flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                        {activeTab === 'compose' ? 'border-indigo-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'} min-h-[44px] min-w-[44px]"
                        on:click={() => activeTab = 'compose'}
                    >
                        <Layers size={16} /> docker-compose.yml
                    </button>
                    <button
                        class="flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                        {activeTab === 'env' ? 'border-indigo-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'} min-h-[44px] min-w-[44px]"
                        on:click={() => activeTab = 'env'}
                    >
                        <FileText size={16} /> .env
                    </button>
                    <button
                        class="flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                        {activeTab === 'ignore' ? 'border-indigo-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'} min-h-[44px] min-w-[44px]"
                        on:click={() => activeTab = 'ignore'}
                    >
                        <FileCode size={16} /> .dockerignore
                    </button>
                </div>

                <!-- Code Area -->
                <div class="p-0">
                    <CodePreview code={previewCode} language={previewLang} />
                </div>
            </div>
        </div>

    </div>

    <!-- Documentation -->
    <!-- JSON-LD for SEO -->
  <!-- eslint-disable-next-line @typescript-eslint/no-unused-expressions -->
    {@html '<script type="application/ld+json">' + JSON.stringify({
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
        "@id": "https://selfgrowingmicrotool.com/" + lang + "/tools/deploy-forge",
      "isAccessibleForFree": true,
      "name": "Deploy Forge",
      "applicationCategory": "DeveloperApplication",
      "operatingSystem": "Web",
      "offers": {
        "@type": "Offer",
        "price": "0",
        "priceCurrency": "USD"
      },
      "description": dict.tools.deployForge.description,
      "featureList": "Dockerfile generation, Docker Compose builder, Multi-stage build optimization"
    }) + '</script>'}

  <!-- eslint-disable-next-line @typescript-eslint/no-unused-expressions -->
    {@html '<script type="application/ld+json">' + JSON.stringify({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": faqItems.map(f => ({
        "@type": "Question",
        "name": f.q,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": f.a
        }
      }))
    }) + '</script>'}

    <div class="mt-20 border-t border-slate-800 pt-16">
        <div class="prose prose-invert max-w-none">
            <h2 class="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-cyan-400 mb-6">
                {dict.tools.deployForge.guide.title}
            </h2>
            <div class="grid md:grid-cols-2 gap-12 text-slate-300 leading-relaxed">
                <div>
                    <h3 class="text-xl font-semibold text-white mb-4">{dict.tools.deployForge.guide.introTitle}</h3>
                    <p class="mb-4">
                        {dict.tools.deployForge.guide.intro}
                    </p>
                </div>
                <div>
                    <h3 class="text-xl font-semibold text-white mb-4">{dict.tools.deployForge.guide.featuresTitle}</h3>
                    <div class="space-y-3 markdown-content">
                        <!-- We render these as markdown-like lists -->
                        <div class="flex items-start gap-2">
                            <span class="text-indigo-400 mt-1">•</span>
                            <span>{@html dict.tools.deployForge.guide.f1.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</span>
                        </div>
                        <div class="flex items-start gap-2">
                            <span class="text-indigo-400 mt-1">•</span>
                            <span>{@html dict.tools.deployForge.guide.f2.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</span>
                        </div>
                        <div class="flex items-start gap-2">
                            <span class="text-indigo-400 mt-1">•</span>
                            <span>{@html dict.tools.deployForge.guide.f3.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="mt-12">
                <GuideSection {...dict?.guide} />
  <AdPlaceholder />
  <FAQSection
                    title={dict.tools.deployForge.faqTitle}
                    items={faqItems}
                />
            </div>
        </div>
    </div>

  <div class="mt-12 mb-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <RelatedTools {lang} currentSlug="deploy-forge" currentCategory="dev" />
  </div>
</main>
</div>
