<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { getDictionary } from '$lib/dictionaries';
  import { MoveLeft, Download, Save, History, Share2, FileCode, Layers, FileJson, FileText } from 'lucide-svelte';
  import JSZip from 'jszip';

  import StackSelector from './components/StackSelector.svelte';
  import DatabaseSelector from './components/DatabaseSelector.svelte';
  import ConfigPanel from './components/ConfigPanel.svelte';
  import CodePreview from './components/CodePreview.svelte';

  import { STACKS } from '$lib/utils/deploy-forge/defaults';
  import type { StackId, ProjectConfig, DatabaseId } from '$lib/utils/deploy-forge/types';
  import { generateDockerfile, generateDockerignore } from '$lib/utils/deploy-forge/generator';
  import { generateCompose, generateEnv, generateEnvExample } from '$lib/utils/deploy-forge/compose';
  import { saveProject, getProjects, db } from '$lib/db/deploy-forge';

  // --- State ---
  $: lang = $page.params.lang || 'en';
  // Fallback for missing dictionary entries if any
  $: dict = getDictionary(lang);

  let currentStackId: StackId = 'node';
  let config: ProjectConfig = {
      port: 3000,
      baseImage: 'node:20-alpine',
      envVars: [],
      databases: [],
      buildCmd: '',
      startCmd: ''
  };

  let activeTab: 'dockerfile' | 'compose' | 'env' | 'ignore' = 'dockerfile';
  let showHistory = false;

  // --- Reactivity ---
  $: dockerfile = generateDockerfile(currentStackId, config);
  $: compose = generateCompose(config);
  $: envFile = generateEnv(config);
  $: envExampleFile = generateEnvExample(config);
  $: dockerIgnore = generateDockerignore(currentStackId);

  $: previewCode = activeTab === 'dockerfile' ? dockerfile
                 : activeTab === 'compose' ? compose
                 : activeTab === 'env' ? envFile
                 : dockerIgnore;

  $: previewLang = activeTab === 'dockerfile' ? 'docker'
                 : activeTab === 'compose' ? 'yaml'
                 : activeTab === 'env' ? 'bash' // close enough
                 : 'plaintext';

  // --- Actions ---

  function handleStackSelect(e: CustomEvent<StackId>) {
      const newStackId = e.detail;
      if (newStackId === currentStackId) return;

      currentStackId = newStackId;
      const def = STACKS.find(s => s.id === newStackId);
      if (def) {
          config = {
              ...config,
              baseImage: def.defaultImage,
              port: def.defaultPort,
              buildCmd: '', // Reset commands as they are stack specific
              startCmd: ''
          };
      }
  }

  function handleDbChange(e: CustomEvent<DatabaseId[]>) {
      config.databases = e.detail;
  }

  async function downloadProject() {
      const zip = new JSZip();

      zip.file('Dockerfile', dockerfile);
      zip.file('docker-compose.yml', compose);
      zip.file('.dockerignore', dockerIgnore);
      zip.file('.env', envFile);
      zip.file('.env.example', envExampleFile);

      // Add README
      zip.file('README.md', `# Project Configuration\n\nGenerated by Deploy Forge.\n\n## Stack\n- ${currentStackId}\n- Base Image: ${config.baseImage}\n\n## Usage\n\n\`\`\`bash\ndocker-compose up --build\n\`\`\``);

      const content = await zip.generateAsync({ type: 'blob' });
      const url = window.URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = `deploy-forge-${currentStackId}.zip`;
      a.click();
      window.URL.revokeObjectURL(url);
  }

  async function saveToHistory() {
      await saveProject({
          id: crypto.randomUUID(),
          name: `${currentStackId} - ${new Date().toLocaleTimeString()}`,
          stackId: currentStackId,
          config: { ...config }, // Clone
          updatedAt: Date.now()
      });
      // Show toast or feedback?
      alert('Project saved to local history!');
  }
</script>

<svelte:head>
  <title>Deploy Forge: Dockerfile Generator | {dict.home.title}</title>
  <meta name="description" content="The definitive container configuration architect. Generate production-ready Dockerfiles and Docker Compose files for Node.js, Python, Go, Rust, and more." />
  <meta name="keywords" content="dockerfile generator, docker compose builder, container architect, devops tool" />
</svelte:head>

<div class="min-h-screen bg-slate-900 text-slate-100 pb-20">
  <!-- Header -->
  <header class="bg-slate-800/50 backdrop-blur-md border-b border-slate-700/50 sticky top-0 z-30">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
      <div class="flex items-center space-x-4">
        <a href="/{lang}" class="p-2 hover:bg-slate-700 rounded-full transition-colors group" aria-label="Back">
          <MoveLeft size={20} class="text-slate-400 group-hover:text-white" />
        </a>
        <h1 class="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-cyan-400">
          Deploy Forge
        </h1>
      </div>
      <div class="flex items-center space-x-2">
         <button on:click={saveToHistory} class="p-2 hover:bg-slate-700 rounded-lg text-slate-400 hover:text-white transition-colors" aria-label="Save">
            <Save size={20} />
         </button>
         <button on:click={downloadProject} class="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium transition-colors text-sm">
            <Download size={18} />
            <span>Download</span>
         </button>
      </div>
    </div>
  </header>

  <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">

        <!-- Left Column: Config (5 cols) -->
        <div class="lg:col-span-5 space-y-8">
            <section>
                <h2 class="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">Select Stack</h2>
                <StackSelector
                    selectedStackId={currentStackId}
                    on:select={handleStackSelect}
                />
            </section>

            <section class="bg-slate-900/50 p-6 rounded-2xl border border-slate-800">
                <ConfigPanel
                    bind:config
                    stackId={currentStackId}
                />
            </section>

            <section>
                <h2 class="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">Add Services</h2>
                <DatabaseSelector
                    selectedDatabases={config.databases}
                    on:change={handleDbChange}
                />
            </section>
        </div>

        <!-- Right Column: Preview (7 cols) -->
        <div class="lg:col-span-7">
            <div class="bg-slate-800 rounded-2xl border border-slate-700 shadow-xl overflow-hidden sticky top-24">
                <!-- Tabs -->
                <div class="flex items-center border-b border-slate-700 bg-slate-900/50 overflow-x-auto">
                    <button
                        class="flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                        {activeTab === 'dockerfile' ? 'border-indigo-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'}"
                        on:click={() => activeTab = 'dockerfile'}
                    >
                        <FileCode size={16} /> Dockerfile
                    </button>
                    <button
                        class="flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                        {activeTab === 'compose' ? 'border-indigo-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'}"
                        on:click={() => activeTab = 'compose'}
                    >
                        <Layers size={16} /> docker-compose.yml
                    </button>
                    <button
                        class="flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                        {activeTab === 'env' ? 'border-indigo-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'}"
                        on:click={() => activeTab = 'env'}
                    >
                        <FileText size={16} /> .env
                    </button>
                    <button
                        class="flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap
                        {activeTab === 'ignore' ? 'border-indigo-500 text-white bg-slate-800' : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'}"
                        on:click={() => activeTab = 'ignore'}
                    >
                        <FileCode size={16} /> .dockerignore
                    </button>
                </div>

                <!-- Code Area -->
                <div class="p-0">
                    <CodePreview code={previewCode} language={previewLang} />
                </div>
            </div>
        </div>

    </div>

    <!-- Documentation -->
    <!-- JSON-LD for SEO -->
    {@html `<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      "name": "Deploy Forge",
      "applicationCategory": "DeveloperApplication",
      "operatingSystem": "Web",
      "offers": {
        "@type": "Offer",
        "price": "0",
        "priceCurrency": "USD"
      },
      "description": "The definitive container configuration architect. Generate production-ready Dockerfiles and Docker Compose files.",
      "featureList": "Dockerfile generation, Docker Compose builder, Multi-stage build optimization"
    }
    </script>`}

    <div class="mt-20 border-t border-slate-800 pt-16">
        <div class="prose prose-invert max-w-none">
            <h2 class="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-cyan-400 mb-6">
                The Definitive Container Architect
            </h2>
            <div class="grid md:grid-cols-2 gap-12 text-slate-300 leading-relaxed">
                <div>
                    <h3 class="text-xl font-semibold text-white mb-4">Why Deploy Forge?</h3>
                    <p class="mb-4">
                        Containerization is the backbone of modern infrastructure, but writing
                        <code class="text-indigo-300 bg-slate-800 px-1 py-0.5 rounded">Dockerfiles</code> from scratch is error-prone and tedious.
                        Deploy Forge bridges the gap between development and operations by generating production-grade configurations instantly.
                    </p>
                    <p>
                        Whether you are a startup scaling a Node.js microservice or an enterprise deploying a Rust backend,
                        Deploy Forge ensures your containers are secure, optimized, and ready for the cloud.
                    </p>
                </div>
                <div>
                    <h3 class="text-xl font-semibold text-white mb-4">Pro-Grade Engineering</h3>
                    <ul class="space-y-3">
                        <li class="flex items-start gap-2">
                            <span class="text-indigo-400 mt-1">•</span>
                            <span><strong>Multi-Stage Builds:</strong> Automatically minimizes image size by separating build and runtime environments.</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <span class="text-indigo-400 mt-1">•</span>
                            <span><strong>Security First:</strong> Generates non-root user configurations and proper secret handling patterns.</span>
                        </li>
                         <li class="flex items-start gap-2">
                            <span class="text-indigo-400 mt-1">•</span>
                            <span><strong>Full Stack Ready:</strong> One-click integration for Databases (Postgres, Redis) and Web Servers (Nginx).</span>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="mt-12 bg-slate-900 rounded-2xl p-8 border border-slate-800">
                <h3 class="text-2xl font-bold text-white mb-6">Frequently Asked Questions</h3>
                <div class="space-y-6">
                    <div>
                        <h4 class="font-medium text-lg text-white mb-2">Is my configuration data sent to a server?</h4>
                        <p class="text-slate-400">No. Deploy Forge runs entirely in your browser using local logic. Your proprietary build commands and environment variables never leave your device.</p>
                    </div>
                    <div>
                        <h4 class="font-medium text-lg text-white mb-2">What is a Multi-Stage Build?</h4>
                        <p class="text-slate-400">A Docker feature that allows you to use intermediate images to compile code, then copy only the artifacts to a final, slimmer image. This drastically reduces the final container size and improves security.</p>
                    </div>
                    <div>
                        <h4 class="font-medium text-lg text-white mb-2">Can I use this for production?</h4>
                        <p class="text-slate-400">Yes. The generated files follow industry best practices. However, you should always review the configuration to ensure it meets your specific organizational compliance requirements.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </main>
</div>
