import type { ProjectConfig, StackId } from './types';

export function generateDockerfile(stackId: StackId, config: ProjectConfig): string {
  const parts: string[] = [];
  const { baseImage, buildCmd, startCmd, port, envVars } = config;

  // Header
  parts.push(`# Generated by Deploy Forge`);
  parts.push(`# ${new Date().toISOString()}`);
  parts.push(``);

  if (stackId === 'node') {
    parts.push(`FROM ${baseImage}`);
    parts.push(`WORKDIR /app`);
    parts.push(``);
    parts.push(`# Install dependencies`);
    parts.push(`COPY package*.json ./`);
    parts.push(`RUN npm ci`);
    parts.push(``);
    parts.push(`# Copy source`);
    parts.push(`COPY . .`);
    parts.push(``);

    if (buildCmd) {
      parts.push(`# Build`);
      parts.push(`RUN ${buildCmd}`);
      parts.push(``);
    }

    parts.push(`# Environment`);
    parts.push(`ENV NODE_ENV=production`);
    parts.push(`EXPOSE ${port}`);

    // Add env vars that are not secret
    envVars.forEach(env => {
      if (!env.isSecret) {
        parts.push(`ENV ${env.key}=${env.value}`);
      }
    });

    parts.push(``);
    if (startCmd) {
        // Split command into array for exec form
        const cmdParts = startCmd.split(' ').map(s => `"${s}"`).join(', ');
        parts.push(`CMD [${cmdParts}]`);
    } else {
        parts.push(`CMD ["npm", "start"]`);
    }

  } else if (stackId === 'python') {
    parts.push(`FROM ${baseImage}`);
    parts.push(`WORKDIR /app`);
    parts.push(``);
    parts.push(`# Install dependencies`);
    parts.push(`COPY requirements.txt .`);
    parts.push(`RUN pip install --no-cache-dir -r requirements.txt`);
    parts.push(``);
    parts.push(`# Copy source`);
    parts.push(`COPY . .`);
    parts.push(``);

    parts.push(`EXPOSE ${port}`);
    envVars.forEach(env => {
        if (!env.isSecret) parts.push(`ENV ${env.key}=${env.value}`);
    });
    parts.push(``);

    if (startCmd) {
        const cmdParts = startCmd.split(' ').map(s => `"${s}"`).join(', ');
        parts.push(`CMD [${cmdParts}]`);
    }

  } else if (stackId === 'go') {
    // Multi-stage for Go
    parts.push(`# Build Stage`);
    parts.push(`FROM ${baseImage} AS builder`);
    parts.push(`WORKDIR /app`);
    parts.push(`COPY go.mod go.sum ./`);
    parts.push(`RUN go mod download`);
    parts.push(`COPY . .`);
    parts.push(`RUN ${buildCmd || 'go build -o main .'}`);
    parts.push(``);
    parts.push(`# Production Stage`);
    parts.push(`FROM alpine:latest`);
    parts.push(`WORKDIR /app`);
    parts.push(`COPY --from=builder /app/${buildCmd ? buildCmd.split(' -o ')[1].split(' ')[0] : 'main'} .`);
    parts.push(``);
    parts.push(`EXPOSE ${port}`);
    envVars.forEach(env => {
        if (!env.isSecret) parts.push(`ENV ${env.key}=${env.value}`);
    });
    parts.push(`CMD ["./${buildCmd ? buildCmd.split(' -o ')[1].split(' ')[0] : 'main'}"]`);

  } else if (stackId === 'rust') {
    parts.push(`# Build Stage`);
    parts.push(`FROM ${baseImage} AS builder`);
    parts.push(`WORKDIR /app`);
    parts.push(`COPY . .`);
    parts.push(`RUN ${buildCmd || 'cargo build --release'}`);
    parts.push(``);
    parts.push(`# Production Stage`);
    parts.push(`FROM debian:buster-slim`);
    parts.push(`WORKDIR /app`);
    // Assuming standard cargo output structure
    parts.push(`COPY --from=builder /app/target/release/app .`);
    parts.push(`EXPOSE ${port}`);
    parts.push(`CMD ["./app"]`);

  } else if (stackId === 'static') {
    parts.push(`FROM ${baseImage}`);
    parts.push(`COPY . /usr/share/nginx/html`);
    parts.push(`EXPOSE 80`);
    parts.push(`CMD ["nginx", "-g", "daemon off;"]`);
  }

  return parts.join('\n');
}

export function generateDockerignore(stackId: StackId): string {
    const common = [
        '.git',
        '.gitignore',
        '.env',
        'docker-compose.yml',
        'Dockerfile',
        'README.md'
    ];

    if (stackId === 'node') {
        return [...common, 'node_modules', 'npm-debug.log', 'dist', 'build'].join('\n');
    }
    if (stackId === 'python') {
        return [...common, '__pycache__', '*.pyc', 'venv', '.pytest_cache'].join('\n');
    }
    if (stackId === 'go' || stackId === 'rust') {
        return [...common, 'target', 'vendor'].join('\n');
    }

    return common.join('\n');
}
