<script lang="ts">
  import { fade } from 'svelte/transition';
  import { getDictionary } from '$lib/dictionaries';

  export let cronExpression: string;
  export let description: string;
  export let lang: string = 'en';

  $: dict = getDictionary(lang).tools.cronEditor;

  let showToast = false;
  let toastMessage = '';

  function triggerToast(msg: string) {
      toastMessage = msg;
      showToast = true;
      setTimeout(() => showToast = false, 2000);
  }

  async function copyToClipboard() {
      try {
          await navigator.clipboard.writeText(cronExpression);
          triggerToast(dict.feedback.copied);
      } catch (err) {
          console.error('Failed to copy:', err);
      }
  }

  async function shareUrl() {
      const url = new URL(window.location.href);
      url.searchParams.set('cron', cronExpression);

      if (navigator.share) {
          try {
              await navigator.share({
                  title: 'Cronos',
                  text: description,
                  url: url.toString()
              });
          } catch (err) {
              // Ignore abort
          }
      } else {
          try {
              await navigator.clipboard.writeText(url.toString());
              triggerToast(dict.feedback.copied);
          } catch (err) {
              console.error('Failed to copy link:', err);
          }
      }
  }

  function downloadCrontab() {
      const content = `# Generated by Cronos\n# ${description}\n${cronExpression} my-script.sh\n`;
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'cron-job.txt';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      triggerToast(dict.feedback.downloadStarted);
  }
</script>

<div class="flex items-center space-x-2">
  <button
    class="flex items-center space-x-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors font-medium text-sm"
    on:click={copyToClipboard}
    title={`${dict.buttons.copy} (Ctrl+S)`}
  >
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>
    <span>{dict.buttons.copy}</span>
  </button>

  <button
    class="p-2 bg-white/5 hover:bg-white/10 text-gray-300 hover:text-white rounded-lg transition-colors border border-white/10"
    on:click={shareUrl}
    title={dict.buttons.share}
    aria-label="Share"
  >
     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><polyline points="16 6 12 2 8 6"/><line x1="12" x2="12" y1="2" y2="15"/></svg>
  </button>

  <button
    class="p-2 bg-white/5 hover:bg-white/10 text-gray-300 hover:text-white rounded-lg transition-colors border border-white/10"
    on:click={downloadCrontab}
    title={dict.buttons.download}
    aria-label="Download"
  >
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>
  </button>

  {#if showToast}
     <div class="fixed bottom-8 left-1/2 -translate-x-1/2 bg-gray-900 text-white px-4 py-2 rounded-full shadow-xl border border-white/10 text-sm z-50 flex items-center" transition:fade>
         <span class="mr-2">✨</span> {toastMessage}
     </div>
  {/if}
</div>
